spring:
  datasource:
#    username: sa
#    password: ""
#    url: jdbc:h2:mem:a
#    driver-class-name: org.h2.Driver
#
    list:
      - name: ds_a
        username: sa
        password: ""
        url: jdbc:h2:mem:a
        driver-class-name: org.h2.Driver
        schema: db/schemaA.sql
      - name: ds_b
        username: sa
        password: ""
        url: jdbc:h2:mem:b
        driver-class-name: org.h2.Driver
        schema: db/schemaA.sql

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'NULL'
    default-fetch-size: 500
  mapper-locations: mapper/*.xml

logging:
  level:
    com.github.xiaoy.samples: debug